### ISSUE TITLE
bug: Failure to Upgrade to `v0.5.0` due to bucket name change

### ISSUE THREAD

**Issue by RobertSheehyAtFanatics** [lacework/terraform-aws-eks-audit-log#33]
**Describe the bug**
When upgrading from v0.4.4 to v0.5.0. https://github.com/lacework/terraform-aws-eks-audit-log/compare/v0.4.4...v0.5.0 We get the following error, when trying to apply this module.
```
Error: deleting Amazon S3 (Simple Storage) Bucket (lw-eks-xxxxxx): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket. status code: 409
```

**Steps to reproduce**
Initialize and apply this module on version and `v0.4.4`, then upgrade it to `v0.5.0`.

**Expected behavior**
I'd expect, without changing any inputs, the upgrade should work and our existing bucket shouldn't be deleted.

**Please complete the following information):**
 - Terraform Version: v1.3.1
 - Module Version: v0.5.0

**Additional context**
I think this is the problem. 
https://github.com/lacework/terraform-aws-eks-audit-log/commit/6f8962d88bfa2911bd20728389ae8818969902ec#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbL2-R7

This commit changed the default bucket name from `${var.prefix}${random_id.uniq.hex}` to `${var.prefix}-bucket-${random_id.uniq.hex}`, which triggers the s3 delete.

**Comment by karlpvoss** [comment]
Can replicate the symptoms here. Name change of the bucket here:

```
# module.aws_eks_audit_log.aws_s3_bucket.log_bucket[0] must be replaced
-/+ resource "aws_s3_bucket" "log_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      ~ arn                         = "arn:aws:s3:::lw-eks-alXXXXXXXX-access-logs" -> (known after apply)
      ~ bucket                      = "lw-eks-alXXXXXXXX-access-logs" -> "lw-eks-al-bucket-XXXXXXXX-access-logs" # forces replacement
```

Can't delete the bucket since the `bucket_force_delete` wasn't set:

```
Error: deleting S3 Bucket (lw-eks-al26051264): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
```

Just a heads up that the newly-created example for `use_existing_bucket` is missing a `README`, and presents on the Terraform docs as an internal-only module: https://github.com/lacework/terraform-aws-eks-audit-log/tree/main/examples/use_existing_bucket

![Screenshot 2023-04-24 at 15 36 10](https://user-images.githubusercontent.com/13564686/235394020-12a2557b-241b-41d9-927c-eabe1d0d2b3d.png)

**Comment by karlpvoss** [comment]
Can replicate the symptoms here. Name change of the bucket here:

```
# module.aws_eks_audit_log.aws_s3_bucket.log_bucket[0] must be replaced
-/+ resource "aws_s3_bucket" "log_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      ~ arn                         = "arn:aws:s3:::lw-eks-alXXXXXXXX-access-logs" -> (known after apply)
      ~ bucket                      = "lw-eks-alXXXXXXXX-access-logs" -> "lw-eks-al-bucket-XXXXXXXX-access-logs" # forces replacement
```

Can't delete the bucket since the `bucket_force_delete` wasn't set:

```
Error: deleting S3 Bucket (lw-eks-alXXXXXXXX): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
```

Just a heads up that the newly-created example for `use_existing_bucket` is missing a `README`, and presents on the Terraform docs as an internal-only module: https://github.com/lacework/terraform-aws-eks-audit-log/tree/main/examples/use_existing_bucket

![Screenshot 2023-04-24 at 15 36 10](https://user-images.githubusercontent.com/13564686/235394020-12a2557b-241b-41d9-927c-eabe1d0d2b3d.png)

**Comment by karlpvoss** [comment]
This appears to have been resolved in this PR: https://github.com/lacework/terraform-aws-eks-audit-log/pull/34

**Comment by afiune** [comment]
@karlpvoss @RobertSheehyAtFanatics Thank you for your feedback, we have indeed solved this issue with https://github.com/lacework/terraform-aws-eks-audit-log/pull/34

If you have more issues, please let us know.
